{
 "title": "Lowstock",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Etsy Listings",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etsy_updates_total[1m])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Telegram Commands",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tg_commands_total[1m])) by (command, user_id)",
     "legendFormat": "{{command}} {{user_id}}"
    },
    {
     "expr": "sum(rate(tg_commands_total[1m])) by (command)",
     "legendFormat": "{{command}} total"
    }
   ]
  },
  { "title": "APIs success/failure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Etsy Feeds API calls Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etsy_feeds_api_calls{status=\"success\"}[1m]))",
     "legendFormat": "Calls"
    }
   ]
  },
  {
   "title": "Etsy Feeds API calls Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etsy_feeds_api_calls{status=\"failure\"}[1m]))",
     "legendFormat": "Calls"
    }
   ]
  },
  {
   "title": "Etsy API calls Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etsy_feeds_api_calls{status=\"success\"}[1m]))",
     "legendFormat": "Calls"
    }
   ]
  },
  {
   "title": "Etsy API calls Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etsy_feeds_api_calls{status=\"failure\"}[1m]))",
     "legendFormat": "Calls"
    }
   ]
  },
  {
   "title": "Telegram API calls Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tg_api_calls{status=\"success\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Telegram API calls Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tg_api_calls{status=\"failure\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}